language: python

sudo: false

python:
#  - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"

jdk:
  - "oraclejdk8"

#env:
  # different connection classes to test
#  - TEST_ES_CONNECTION=Urllib3HttpConnection
#  - TEST_ES_CONNECTION=RequestsHttpConnection

install:
  - wget -O /tmp/es.zip "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=org.elasticsearch.distribution.zip&a=elasticsearch&e=zip&v=2.4.1"
  - unzip /tmp/es.zip -d /tmp/
  - mv /tmp/elasticsearch-2.4.1 /tmp/elasticsearch
  - /tmp/elasticsearch/bin/elasticsearch -E script.inline=true -E path.repo=/tmp -E repositories.url.allowed_urls='http://*' -E node.attr.testattr=test
#  - git clone https://github.com/elastic/elasticsearch.git ../elasticsearch
  - pip install .

script:
  - python setup.py test