language: python

sudo: false

python:
#  - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"

jdk:
  - "oraclejdk8"

env:
  # different connection classes to test
#  - TEST_ES_CONNECTION=RequestsHttpConnection
  # ES 2.4.2
  - TEST_ES_CONNECTION=Urllib3HttpConnection ES_VER=2.4.2 IS_ES_SECURED=true SG_VER=2.4.2.9 SG_SSL_VER=2.4.2.19 ES_CONF=./tests/conf ES_HOME=/tmp/elasticsearch TMP_DIR=/tmp
  - TEST_ES_CONNECTION=Urllib3HttpConnection ES_VER=2.4.2 IS_ES_SECURED=false ES_CONF=./tests/conf ES_HOME=/tmp/elasticsearch TMP_DIR=/tmp
  # ES 2.4.4
  - TEST_ES_CONNECTION=Urllib3HttpConnection ES_VER=2.4.4 IS_ES_SECURED=true SG_VER=2.4.4.10 SG_SSL_VER=2.4.4.19 ES_CONF=./tests/conf ES_HOME=/tmp/elasticsearch TMP_DIR=/tmp
  - TEST_ES_CONNECTION=Urllib3HttpConnection ES_VER=2.4.4 IS_ES_SECURED=false ES_CONF=./tests/conf ES_HOME=/tmp/elasticsearch TMP_DIR=/tmp

install:
  - wget -O /tmp/es.zip "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=org.elasticsearch.distribution.zip&a=elasticsearch&e=zip&v=${ES_VER}"
  - unzip /tmp/es.zip -d ${TMP_DIR}
  - mv /tmp/elasticsearch-${ES_VER} ${ES_HOME}
  # Install and setup Elasticsearch & SearchGuard plugins
  - chmod u+x ./tests/setup/sg_init.sh
  - ./tests/setup/sg_init.sh
  - pip install -e .[test]

script:
  - python setup.py test