from watches.commands.cluster_health import ClusterHealth as cluster_health
from watches.commands.cluster_state import ClusterState as cluster_state
from watches.commands.cluster_stats import ClusterStats as cluster_stats
from watches.commands.nodes_stats import NodesStats as nodes_stats
from watches.commands.nodes_info import NodesInfo as nodes_info
from watches.commands.indices_stats import IndicesStats as indices_stats
from watches.commands.nodes_hotthreads import NodesHotThreads as nodes_hotthreads
from watches.commands.just_nodes_stats import JustNodesStats as just_nodes_stats
from watches.commands.just_indices_stats import JustIndicesStats as just_indices_stats
